version: '3.8'
services:
  k6:
    image: grafana/k6
    command: run  /tmp/script.js
    volumes:
      - ./test/script.js:/tmp/script.js

  web:
    deploy:
      replicas : 3
    image: registry.gitlab.com/pongphat/lab01:latest

  # web_1:
  #   image: registry.gitlab.com/pongphat/lab01:latest
  
  # web_2:
  #   image: registry.gitlab.com/pongphat/lab01:latest
  
  # web_3:
  #   image: registry.gitlab.com/pongphat/lab01:latest
  
  nginx:
    image: nginx
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf  
    ports:
      - "3001:80"
    # depends_on:
    #   - web_1  

    
    

       